Feat/imb 49
Immobylette/immobylette--api-main pull request #1
Opened 2024-04-08 09:41 UTC by OdakK

IMB 49

2024-04-08 09:50 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Créer les entities](https://trello.com/c/kUE1jDl2/46-cr%C3%A9er-les-entities)

2024-04-08 09:50 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Créer les DTOs](https://trello.com/c/xbqM5rbc/47-cr%C3%A9er-les-dtos)

2024-04-08 09:50 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implémenter la feature agent](https://trello.com/c/AZCNyWaV/49-impl%C3%A9menter-la-feature-agent)

2024-04-08 10:06 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/domain/ThirdPartyTypeEnum.java
> +    TENANT("TENANT");
Il y aura aussi OWNER

2024-04-08 11:07 UTC, patacoing requested changes

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/dto/PropertyDto.java
Il manque les champs current_inventory et photo

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/dto/PropertySummaryDto.java
tu n'as pas fait le mapping : @JsonProperty("...")

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/dto/PropertySummaryDto.java
> +    private Boolean currently_inventory;
le nom est current_inventory

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/dto/StepDto.java
> +    private List<MultipartFile> photos;
tu es sur que les photos seront passées dans le body ? c'est pas dans les headers ça ?

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Address.java
Il manque l'auto génération de l'UUID ? et donc dans toutes les autres entities

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/dto/AddressDto.java
Il manque le @NotNull sur certains champs et donc également dans tous les autres Dto

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Address.java
Il manque les not null ?

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Element.java
> +    private String photo;
c'est un UUID

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Element.java
> +    private String photoFolder;
UUID

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/HeatingType.java
> +@Table(name = "hot_water_types")
c'est heating_types

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Inventory.java
> +    private String inventoryDate;
c'est un Date

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Inventory.java
> +    private Lease fkLease;
dans certains cas tu mets fkChamp et dans d'autres tu mets champ faut choisir entre les 2

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Property.java
> +
manque thirdPartyOwner, refPhotoFolder, nbRooms, surface et il ya des champs en trop

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/PropertyClass.java
> +@Table(name = "property_types")
property_classes

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/RoomType.java
> +    @Column(name = "surname")
c'est label le champ en bdd

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/SignatureInventoryThirdParty.java
pas de fk ?

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/SignatureInventoryThirdPartyId.java
Quel est l'intérêt de ce fichier ?

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Step.java
> +    private InventoryType inventoryType;
pourquoi InventoryType ? c'est un Inventory tout cours

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/ThirdParty.java
> +    private String bankDetails;
tu n'as pas mis les contraintes sur le varchar

2024-04-08 11:07 UTC, patacoing commented on src/main/java/com/immobylette/api/main/domain/ThirdPartyTypeEnum.java
manque owner

2024-04-08 11:09 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Configuration de la bdd](https://trello.com/c/dXgAaRMB/50-configuration-de-la-bdd)

2024-04-08 12:10 UTC, OdakK commented on src/main/java/com/immobylette/api/main/entity/SignatureInventoryThirdPartyId.java
C'est pour des clés primaire multiples

2024-04-08 12:21 UTC, OdakK commented on src/main/java/com/immobylette/api/main/dto/StepDto.java
> +    private List<MultipartFile> photos;
Ce sera pas dans le body

2024-04-08 17:29 UTC, patacoing requested changes
Tu n'as pas mis les NotNull sur les Dto

2024-04-08 17:29 UTC, patacoing commented on src/main/java/com/immobylette/api/main/dto/PropertySummaryDto.java
> +    private UUID photo;
la photo est un string car c'est l'url pour y accéder

2024-04-08 17:29 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Element.java
> +    @Column(name = "ref_photo_folder")
c'est ref_photos_folder

2024-04-08 17:29 UTC, patacoing commented on src/main/java/com/immobylette/api/main/entity/Property.java
> +    @JoinColumn(name = "fk__third_party_owner")
il ya un _ en trop

2024-04-08 21:53 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/dto/PropertySummaryDto.java
> +    private UUID photo;
(du coup c'est aussi partout où y'a une photo de base (ElementDTO et ElementSummaryDTO))

2024-04-08 22:02 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/entity/Property.java
> +    private ThirdPartyType thirdPartyType;
pourquoi y'a ça dans l'entité Property ?

2024-04-08 22:06 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/entity/StateType.java
> +@Table(name = "property_types")
state_types

2024-04-08 22:07 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/entity/Step.java
> +@Table(name = "leases")
"steps" au lieu de "leases"

2024-04-08 22:10 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/service/ThirdPartyService.java
> +    public List<ThirdPartyDto> getAgents() {
un service c'est pas censé retourné un "ThirdParty" à la place d'un "ThirdPartyDTO"?

2024-04-09 08:18 UTC, OdakK commented on src/main/java/com/immobylette/api/main/service/ThirdPartyService.java
> +    public List<ThirdPartyDto> getAgents() {
non

2024-04-09 12:26 UTC, AlexisPop approved these changes

2024-04-09 12:34 UTC, patacoing approved these changes

2024-04-09 12:34 UTC, patacoing commented on src/main/java/com/immobylette/api/main/dto/InventoryDto.java
on ne l'utilise pas

2024-04-09 12:41 UTC, LfrPaul approved these changes

2024-04-09 12:51 UTC, merged