[ADD] add api photo resource
Immobylette/immobylette--api-main pull request #11
Opened 2024-05-11 14:12 UTC by patacoing

- utilisation de RestClient de spring ==> ajout de la dépendance httpClient
- modif des mappings pour inclure l'url de la photo
- modif dans les services pour récup la photo
- ajout de la resource

Note : je n'ai pas ajouté de méthode pour la gestion des dossiers car pas encore dev côté photo

2024-05-11 14:12 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [implémentation de la ressource de photos](https://trello.com/c/OZiR1Mw3/72-impl%C3%A9mentation-de-la-ressource-de-photos)

2024-05-11 18:58 UTC, LfrPaul requested changes

2024-05-11 18:58 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/service/PropertyService.java
>      public PropertyDto getProperty(UUID id) throws PropertyNotFoundException {
ajouter les 2 exceptions PhotoNotFoundException, GCPStorageException

2024-05-11 18:58 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/controller/PropertyController.java
ajouter les 2 exceptions PhotoNotFoundException, GCPStorageException sur public PropertyDto getProperty

2024-05-13 13:49 UTC, OdakK requested changes

2024-05-13 13:49 UTC, OdakK commented on src/main/java/com/immobylette/api/main/resource/PhotoResource.java
> +@Component
Utiliser l'annotation @AllArgsConstructor

2024-05-13 13:49 UTC, OdakK commented on src/main/java/com/immobylette/api/main/resource/PhotoResource.java
> +        this.restClient = RestClient.builder()
Créer un Bean dans la config  retournant le restClient
Ce bean sera injecté ici dans ressource

2024-05-13 18:14 UTC, OdakK approved these changes

2024-05-15 19:30 UTC, merged