[ADD] Add state endpoint
Immobylette/immobylette--api-main pull request #20
Opened 2024-05-22 17:40 UTC by LfrPaul

Rename Photo to PhotoDto
Rename PhotoDto to PhotoUrlDto

J'ai pas pu utiliser le RestClient qui était fait, j'ai vraiment pas trouvé comment faire pour inclure des MultipartFile dedans avec un formdata, j'ai donc utilisé RestTemplate. Du coup j'ai aussi récup la partie auth de l'autre PR (https://github.com/Immobylette/immobylette--api-main/pull/18) pour éviter de devoir faire le changement plus tard.

Ajout de la méthode pour upload les photos vers l'API Photo

2024-05-22 17:41 UTC, LfrPaul commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter un nouvel état à un élément](https://trello.com/c/DU0V4FlA/108-ajouter-un-nouvel-%C3%A9tat-%C3%A0-un-%C3%A9l%C3%A9ment)

2024-05-29 07:10 UTC, patacoing requested changes

2024-05-29 07:10 UTC, patacoing commented on src/main/java/com/immobylette/api/main/service/StepService.java
> +        Iterator<MultipartFile> photoIterator = photos.iterator();
si les photos et descriptions ne sont pas de la même taille, il faut renvoyer une 400

2024-05-30 15:24 UTC, patacoing approved these changes

2024-05-31 12:33 UTC, AlexisPop approved these changes

2024-05-31 20:58 UTC, merged