[ADD] Start an inventory
Immobylette/immobylette--api-main pull request #5
Opened 2024-04-27 19:12 UTC by LfrPaul

- New POST endpoint in PropertyController
- New service : InventoryService
- New repo :
  - InventoryTypeRepository
  - LeaseRepository

Pour créer le bon type d'état des lieux, je vais récup le label de l'état des lieux N-1, et si c'est entrée, je crée sortie, si c'est sortie je crée entrée 

Retourne 404 si l'agent n'existe pas, ou si la propriété n'a aucun bail associé

2024-04-27 19:12 UTC, LfrPaul commented
![](https://github.trello.services/images/mini-trello-icon.png) [Débuter un état des lieux](https://trello.com/c/ZEaFvBpH/64-d%C3%A9buter-un-%C3%A9tat-des-lieux)

2024-04-29 17:31 UTC, patacoing requested changes

2024-04-29 17:31 UTC, patacoing commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +    public UUID createInventory(UUID propertyId, UUID agentId) {
rajouter le throws avec les exceptions dans la signature de la méthode pour indiquer ce qu'elle peut throw

2024-04-29 17:31 UTC, patacoing commented on src/main/java/com/immobylette/api/main/repository/LeaseRepository.java
> +    Optional<Lease> getLastLeaseByPropertyId(UUID propertyId);
N'y a-t-il pas moyen de le faire sans le @Query, seulement avec le nom de la méthode : 
findFirstByPropertyIdOrderByRentalStartDateDesc ?

2024-04-29 17:31 UTC, patacoing commented on src/main/java/com/immobylette/api/main/repository/InventoryRepository.java
> +            "LIMIT 1"
N'y a-t-il pas moyen de faire sans @Query, avec le nom de la méthode ?

2024-04-29 17:31 UTC, patacoing commented on src/main/java/com/immobylette/api/main/controller/PropertyController.java
> +                               @RequestPart("agent") UUID agentId) throws PropertyNotFoundException {
comment est-ce que tu fait ta requête sur postman en mettant @RequestPart ?
agent=agent_id ?

parce que j'ai l'impression que c'est utilisé pour faire de l'envoie de formulaire

2024-04-29 17:31 UTC, patacoing commented on src/main/java/com/immobylette/api/main/controller/PropertyController.java
> +import org.springframework.web.bind.annotation.*;
A part si on utilises tout les imports dans le fichier, je vois pas pourquoi tout importer

2024-04-29 17:31 UTC, patacoing commented on src/main/java/com/immobylette/api/main/controller/PropertyController.java
> +                               @RequestPart("agent") UUID agentId) throws PropertyNotFoundException {
il manque une exception non ? PropertyNotAssociatedWithAnyLeaseException

2024-04-29 18:28 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/repository/InventoryRepository.java
> +            "LIMIT 1"
j'ai pas réussi vu qu'on veut le champ label de l'inventorytype

2024-04-29 18:29 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/controller/PropertyController.java
> +import org.springframework.web.bind.annotation.*;
c'est mon ide qui le fout automatiquement quand y'a + de 4 imports dans la meme lib j'avais pas vu

2024-04-30 05:40 UTC, patacoing approved these changes

2024-05-03 16:53 UTC, OdakK commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +        String inventoryTypeLabel = inventoryRepository.findLastInventoryType(propertyId).equals("ENTREE")?"SORTIE":"ENTREE";
Extract dans un enum les types d'inventaire

2024-05-03 16:53 UTC, OdakK commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +        inventory.setLease(leaseRepository.findFirstByPropertyIdOrderByRentalStartDateDesc(propertyId).orElseThrow(() -> new PropertyNotAssociatedWithAnyLeaseException(propertyId)));
Extract la recherche de lease dans une variable

2024-05-03 17:59 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +        inventory.setLease(leaseRepository.findFirstByPropertyIdOrderByRentalStartDateDesc(propertyId).orElseThrow(() -> new PropertyNotAssociatedWithAnyLeaseException(propertyId)));
pourquoi faire ça ?

2024-05-07 09:06 UTC, OdakK approved these changes

2024-05-07 18:57 UTC, merged