Feat/imb 68
Immobylette/immobylette--api-main pull request #9
Opened 2024-05-09 10:29 UTC by OdakK

2024-05-09 10:31 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Récupération des éléments](https://trello.com/c/zfzs6JBt/68-r%C3%A9cup%C3%A9ration-des-%C3%A9l%C3%A9ments)

2024-05-09 21:21 UTC, patacoing requested changes

2024-05-09 21:21 UTC, patacoing commented on src/main/java/com/immobylette/api/main/domain/StateTypeEnum.java
> +    MEDIOCRE("MEDIOCRE"),
doit être remplacé par SO_SO("MOYEN")

2024-05-09 21:21 UTC, patacoing commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +    private List<ElementSummaryDto> getElementsByTypes(UUID id, List<String> types) throws InventoryNotFoundException {
le soucis c'est que ducoup dans tes Enum pour les éléments tu vas devoir mettre toutes les catégories possible ?

2024-05-09 21:21 UTC, patacoing commented on src/main/java/com/immobylette/api/main/repository/StepRepository.java
> +            "ORDER BY s.id DESC " +
il ne sert à rien le order by ? les id sont des uuid

2024-05-09 21:21 UTC, patacoing commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +            //TODO: Wait for adding photo resource to populate the photos related attributes
mettre les champs du dto par défaut à 0 dans ce cas, car ils doivent toujours être renvoyés au client

2024-05-09 21:43 UTC, OdakK commented on src/main/java/com/immobylette/api/main/repository/StepRepository.java
> +            "ORDER BY s.id DESC " +
C'est la tech pour les trier par ordre d'insertion en bdd

2024-05-09 21:45 UTC, OdakK commented on src/main/java/com/immobylette/api/main/domain/StateTypeEnum.java
> +    MEDIOCRE("MEDIOCRE"),
![image](https://github.com/Immobylette/immobylette--api-main/assets/78412123/c0faf2a2-5f78-4724-ad66-3cc30219e3e0)

J'ai vu Mediocre en bdd

2024-05-09 21:47 UTC, OdakK commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +            //TODO: Wait for adding photo resource to populate the photos related attributes
ils sont à null actuellement mais je peux mettre à 0 si jamais

2024-05-09 21:48 UTC, OdakK commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +    private List<ElementSummaryDto> getElementsByTypes(UUID id, List<String> types) throws InventoryNotFoundException {
yes faudrait peut être plutôt fonctionner avec une exclusion de mur, sol, plafond pour garder le reste

2024-05-09 21:52 UTC, patacoing commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +            //TODO: Wait for adding photo resource to populate the photos related attributes
oui c'est mieux je pense en attendant

2024-05-09 21:53 UTC, patacoing commented on src/main/java/com/immobylette/api/main/repository/StepRepository.java
> +            "ORDER BY s.id DESC " +
hein mais un uuid ya pas d'ordre, ça a pas de sens de le trier

2024-05-09 21:54 UTC, patacoing commented on src/main/java/com/immobylette/api/main/domain/StateTypeEnum.java
> +    MEDIOCRE("MEDIOCRE"),
ah bah pas bon alors

2024-05-10 16:43 UTC, LfrPaul commented on src/main/java/com/immobylette/api/main/domain/StateTypeEnum.java
> +    MEDIOCRE("MEDIOCRE"),
@patacoing c'était parce que quand j'avais fait le jeu de données, la maquette avait pas encore été traduite en FR, et dans le sujet les états c'est "Neuf, très bon, bon, médiocre, mauvais, très mauvais", j'ai modif au niveau de la maquête

2024-05-11 11:17 UTC, OdakK commented on src/main/java/com/immobylette/api/main/repository/StepRepository.java
> +            "ORDER BY s.id DESC " +
Je sais mais mais c'est ce que j'ai lu sur internet sur du postgresql
On a aucun attribut pour trier sur l'ordre d'insertion

2024-05-11 11:19 UTC, OdakK commented on src/main/java/com/immobylette/api/main/repository/StepRepository.java
> +            "ORDER BY s.id DESC " +
Ou alors faudrait faire une jointure sur Inventory et trier par inventory_date

2024-05-11 11:41 UTC, patacoing requested changes

2024-05-11 11:41 UTC, patacoing commented on src/main/java/com/immobylette/api/main/service/InventoryService.java
> +    private List<ElementSummaryDto> getElementsByTypes(UUID id, List<String> types) throws InventoryNotFoundException {
manque la modif pour ça ducoup

2024-05-13 19:37 UTC, patacoing approved these changes

2024-05-13 22:16 UTC, LfrPaul approved these changes

2024-05-13 22:19 UTC, merged